/**
 * 
 */
package anzen.client.messages;

/**
 * @author mlcs05
 */
public interface Ping {

	/**
	 * This is generated by the client. Use for quick searching.
	 * @return
	 */
	long getClientId();

	/**
	 * The name of the client that is hopefully human readable.
	 * @return The name
	 */
	String getClientName();

	/**
	 * The address of the machine sending the ping. Note this may be on behalf
	 * of another client.
	 * 
	 * @return The senders IP address.
	 */
	String getSendersAddress();
	
	/**
	 * A listing of capabilities provided by the pinging client.
	 * @return The capabilities as an array. Should never be NULL.
	 */
	ClientCapability[] getCapabilities();
}
